### ISSUE TITLE
group-wise one-to-many branch

### ISSUE THREAD

**Issue by xiaopan999** [pnnnnnnn/PrevPredMap#1]
<img width="509" alt="截屏2024-08-05 16 21 58" src="https://github.com/user-attachments/assets/b55e1aed-f463-494e-a4d6-a15284aedbe8">
Hello, I have read your paper and have a question that I would like to consult about. How is the group-wise one-to-many branch in the following figure implemented? Could you share the related code? Thank you!

**Comment by pnnnnnnn** [comment]
Thank you for your interest. We are currently in the process of organizing the code, which comprises the implementation of the group-wise one-to-many branch. Please stay tuned for updates.

**Comment by xiaopan999** [comment]
Is it possible to open-source the code for the "group-wise one-to-many branch" part first?
